### ISSUE TITLE
hi，You can provide the following related depth_ Map

### ISSUE THREAD

**Issue by wudizuixiaosa** [Teragion/Sea-Thru-Impl#1]
You can provide the following related depth_ Map? The correct method is Python graph py --original img_ Path --depth? Can only one image be processed at a time

**Comment by Teragion** [comment]
Currently yes, but with minor changes it can be made to batch process. Honestly speaking it is not quite performant right now, may be downsampling before attenuation computation would make it efficient enough for more images at good resolution. For info about the dataset, please refer to the original authors website http://csms.haifa.ac.il/profiles/tTreibitz/datasets/sea_thru/index.html.

**Comment by wudizuixiaosa** [comment]
thank you for your reply
